name: Manual Workflow

# Only runs when manually triggered
on:
  workflow_dispatch:

jobs:
  build:
    runs-on:  macos-latest
    
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run the artifact upload script
        run: ./BuildScripts/upload_artifacts.sh
        env:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        continue-on-error: false